server:
  port: 2333
  address: 0.0.0.0
lavalink:
  server:
    password: "change-this-password"
    sources:
      youtube: false
      bandcamp: false
      soundcloud: true
      twitch: false
      vimeo: false
      nico: false
      http: true
      local: false
    nonAllocatingFrameBuffer: true
    bufferDurationMs: 200
    frameBufferDurationMs: 2000
    opusEncodingQuality: 4
    resamplingQuality: LOW
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    youtubePlaylistLoadLimit: 3
    playerUpdateInterval: 10
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.1"
      snapshot: false
plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - WEB
      - TV
    clientOptions:
      WEB:
        playback: false
      TV:
        playlistLoading: false
        searching: false
    oauth:
      enabled: true
      refreshToken: "${YOUTUBE_OAUTH_REFRESH_TOKEN}"
      skipInitialization: true

logging:
  level:
    root: WARN
    lavalink: WARN
    dev.lavalink.youtube.http.YoutubeOauth2Handler: INFO
